use_frameworks!

platform :ios, '8.0'

target 'ZHBase_Example' do
  pod 'ZHBase', :path => '../'

  target 'ZHBase_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
